Version: 1.0
setting:
  anti:
    badword:
      enable: true
      list:
        - "fuck"
        - "shit"
        - "你妈"
        - "你个"
        - "脖子右拧"
        - "wdnmd"
        - "艹"
  AutoClean:
    #清理间隔 （单位 秒）
    CleanTime: 360
    CleanMsgAt60s: "[服务器姬] 地面掉落物将在60秒后被清除！！"
    CleanMsgAt10s: "[服务器姬] 地面掉落物将在10秒后被清除！！"
    CleanMsgCountdown: "[服务器姬] 清理倒计时："
    CleanMsgNow: "[服务器姬] 正在清理垃圾....."
    #这个内部的”#“代表了垃圾清理的数量，请勿删除，以免报错
    CleanMsgWhenOver: "[服务器姬] 哟，这次清理了#个垃圾，感觉自己么么哒"


  lang: "zh_CN"